// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlRhIj71sjUY-MMKPnTVIRJ2XAWsP63DY',
    appId: '1:168250828483:web:b575a11ba54042f115e476',
    messagingSenderId: '168250828483',
    projectId: 'fir-bbb7f',
    authDomain: 'fir-bbb7f.firebaseapp.com',
    storageBucket: 'fir-bbb7f.appspot.com',
    measurementId: 'G-3KESZRS789',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa1ECFXqgX-MWyKPTIcBqkverX632ct6k',
    appId: '1:168250828483:android:5045240ec830037815e476',
    messagingSenderId: '168250828483',
    projectId: 'fir-bbb7f',
    storageBucket: 'fir-bbb7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc6uvVyAmGWHRWGNhksBmpes-c394VDK8',
    appId: '1:168250828483:ios:3904b8ffc952970b15e476',
    messagingSenderId: '168250828483',
    projectId: 'fir-bbb7f',
    storageBucket: 'fir-bbb7f.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc6uvVyAmGWHRWGNhksBmpes-c394VDK8',
    appId: '1:168250828483:ios:3904b8ffc952970b15e476',
    messagingSenderId: '168250828483',
    projectId: 'fir-bbb7f',
    storageBucket: 'fir-bbb7f.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlRhIj71sjUY-MMKPnTVIRJ2XAWsP63DY',
    appId: '1:168250828483:web:d5d42ebd2d69275a15e476',
    messagingSenderId: '168250828483',
    projectId: 'fir-bbb7f',
    authDomain: 'fir-bbb7f.firebaseapp.com',
    storageBucket: 'fir-bbb7f.appspot.com',
    measurementId: 'G-FRGP9NHBFQ',
  );
}
