// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ_pFK67eGBN_BT7ncPS5Gqd5gch74lMA',
    appId: '1:437637425338:web:c0178fec40a1c19013fa83',
    messagingSenderId: '437637425338',
    projectId: 'fir-flutter-codelab-f2ad8',
    authDomain: 'fir-flutter-codelab-f2ad8.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f2ad8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFbZir2BMOlrzqQ2QhWZpyPCERUb7tMk',
    appId: '1:437637425338:android:3353249cc30727b613fa83',
    messagingSenderId: '437637425338',
    projectId: 'fir-flutter-codelab-f2ad8',
    storageBucket: 'fir-flutter-codelab-f2ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBY8lW2P0q2pjAmUSHtVhrIN5CaueG9ww',
    appId: '1:437637425338:ios:1af6f6c25d5e587d13fa83',
    messagingSenderId: '437637425338',
    projectId: 'fir-flutter-codelab-f2ad8',
    storageBucket: 'fir-flutter-codelab-f2ad8.appspot.com',
    iosBundleId: 'com.example.firebaseDemoRi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBY8lW2P0q2pjAmUSHtVhrIN5CaueG9ww',
    appId: '1:437637425338:ios:1a3501b31436b69e13fa83',
    messagingSenderId: '437637425338',
    projectId: 'fir-flutter-codelab-f2ad8',
    storageBucket: 'fir-flutter-codelab-f2ad8.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ_pFK67eGBN_BT7ncPS5Gqd5gch74lMA',
    appId: '1:437637425338:web:1d935f1312e4ec9713fa83',
    messagingSenderId: '437637425338',
    projectId: 'fir-flutter-codelab-f2ad8',
    authDomain: 'fir-flutter-codelab-f2ad8.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f2ad8.appspot.com',
  );

}